CMAKE_MINIMUM_REQUIRED(VERSION 3.11)
if (NOT GLEW_FOUND)
    include(FetchContent)
    FetchContent_Declare(GLEW URL https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0.tgz)
    FetchContent_GetProperties(GLEW)
    if (NOT GLEW_POPULATED)
        set(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(GLEW)
        set(BUILD_EXAMPLES OFF)
        add_subdirectory(${glew_SOURCE_DIR}/build/cmake ${glew_BINARY_DIR})
        set(GLEW_FOUND TRUE)
    endif()
endif()
