CMAKE_MINIMUM_REQUIRED(VERSION 3.11)
if (NOT ASSIMP_FOUND)
    include(FetchContent)
    FetchContent_Declare(ASSIMP URL https://github.com/assimp/assimp/archive/refs/tags/v5.1.3.tar.gz)
    FetchContent_GetProperties(ASSIMP)
    if (NOT ASSIMP_POPULATED)
        set(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(ASSIMP)
        set(BUILD_EXAMPLES OFF)
        add_subdirectory(${assimp_SOURCE_DIR} ${assimp_BINARY_DIR})
        set(ASSIMP_FOUND TRUE)
    endif()
endif()
