CMAKE_MINIMUM_REQUIRED(VERSION 3.11)
if (NOT glfw_FOUND)
    INCLUDE(FetchContent)
    FetchContent_Declare(glfw URL https://github.com/glfw/glfw/archive/refs/tags/3.3.7.tar.gz)
    FetchContent_GetProperties(glfw)
    if (NOT glfw_POPULATED)
        SET(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(glfw)
        SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        ADD_SUBDIRECTORY(${glfw_SOURCE_DIR} ${glfw_BINARY_DIR})
        SET(glfw_FOUND TRUE)
    endif()
endif()
