CMAKE_MINIMUM_REQUIRED(VERSION 3.11)
if (NOT GLFW_FOUND)
    include(FetchContent)
    FetchContent_Declare(GLFW URL https://github.com/glfw/glfw/archive/refs/tags/3.3.7.tar.gz)
    FetchContent_GetProperties(GLFW)
    if (NOT GLFW_POPULATED)
        set(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(GLFW)
        set(BUILD_EXAMPLES OFF)
        add_subdirectory(${glfw_SOURCE_DIR} ${glfw_BINARY_DIR})
        set(GLFW_FOUND TRUE)
    endif()
endif()
