_Shader:
  Camera:
    camera.vs
    camera.fs
  Picking:
    camera.vs
    picking.fs
  Selection:
    camera.vs
    selection.fs
  Outline:
    outline.vs
    outline.fs

_Scene:
  Default:
    scene1

_Icon:
  Lush.png
